### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Cyb3rC3lt** [Hagrid29/DumpAADSyncCreds#1]
Hi Hagrid29,

I just wanted to thank you for this tool and more importantly the Use Cases section in regards resetting the password of a user with the Sync account. 

I just managed to get sync account access today but I wonder are we limited to only resetting a password on AAD because I don't want to mess with someone's account but it looks like a quick way to Global Admin? I don't seem to have portal access with the sync account. Also how would you get around their 2FA after resetting the password?

Thanks

**Comment by Hagrid29** [comment]
Hi Cyb3rC3lt,

You could use Sync account to add credential to service principles. If you managed to search a abusable service principles, you could potentially escalate your privilege. You can refer to my another project for details: https://github.com/Hagrid29/AbuseAzureAPIPermissions

Enjoy hunting!

**Comment by Cyb3rC3lt** [comment]
Thank you, that is super useful. I love seeing people's play books 😊. What eventually happened on my test was when I got the Sync creds I logged in via Powershell Module and AAdinternals.

It looked to me as an amateur cloud hacker that they didn't use all the cloud features. I couldn't see any subscriptions (unless this was due to permissions) and when I looked at the GA's they didn't have an immutable ID. When I tried to change their password via Powershell instead I didn't have enough permission.

Dr Nestori then told me that we can only change the password of synced accounts. Not sure why they had a sync server when there wasn't much on the cloud. Maybe they only use it for M365 and I couldn't access it. I tried to list all users with AAdinternals it looked to return users and the screen moved down but no names were listed just a blue screen. Kinda weird. Anway that's how it worked out 😊

**Comment by Hagrid29** [comment]
I thought we still able to change cloud only users' by enumerating their CloudAnchor. ref: https://aadinternals.com/post/on-prem_admin/#getting-global-admin-rights

I am not aware of that change. Thanks for the sharing indeed!

**Comment by Cyb3rC3lt** [comment]
That's a really interesting link, thanks very much. I really need to learn more about it. Here was his response. 

https://twitter.com/DrAzureAD/status/1672310450296352792?t=nP_LhK91XREdsyGWzKp5MA&s=19

He also mentioned 
"But you can make cloud-only user to synced user with AADInternals. But only non-admin users, including those who are GA eligble (if PIM is used).." 

But I didnt understand it to be honest. Maybe you do being more experienced than me on this. Thank you.
